### ISSUE TITLE
include.lowest with inconsistent default

### ISSUE THREAD

**Issue by lorenzwalthert** [jonmcalder/refactor#1]
## Problem

Depending on how breaks are specified, lowest values are included or not. 
- `cut(sample(10), breaks = 2)` gives the levels 1-5 and 6-10 (because the default is overwritten internally on line 78, while
- `cut(sample(10), breaks = c(1, 5, 10)`gives the levels 2-5 and 6-10.
## Suggested solution

Probably due to the default in cut.default, you wanted to keep include.lowest = FALSE. I think it is a counter intuitive default, so let's do away with it and change it to TRUE and hence remove line 78.

**Comment by jonmcalder** [comment]
Yes I agree. Was trying to keep some consistency with cut.default but it is
definitely counter-intuitive for cut.integer so should be changed.

**Comment by lorenzwalthert** [comment]
essentially closed with `4038602`
