### ISSUE TITLE
Performance of cut.integer can be improved

### ISSUE THREAD

**Issue by jonmcalder** [jonmcalder/refactor#13]
Came across [this on StackOverflow](http://stackoverflow.com/questions/21775556/getting-same-output-as-cut-using-speedier-hist-or-findinterval) and it offers around a 5-6x speedup on cut.default, so I figure why not make use of it? (or something similar)

**Comment by lorenzwalthert** [comment]
yes, that's a good idea. Do you want to take the lead there since you are more of an optimization crack than I am?
